### ISSUE TITLE
Unable to connect to PostgreSQL db within Codespace, but works on Azure Data Studio

### ISSUE THREAD

**Issue by CarrieKroutil** [microsoft/vscode-pgsql#93]
**Background** 

- I am able to connect to my PostgreSQL container running in Codespace via Azure Data Studio without issue. 
- Given Azure Data Studio is getting deprecated next year, I wanted to switch over as soon as possible. 

**Describe the bug** 

- I am unable to connect when using this extension on VSCode.

**To Reproduce**

1. Start a new codespace with .devcontainer --> docker-compose.yml file containing:

``` yml
version: '3.8'

networks:
  localnet:
    driver: bridge


services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - localnet

  test-db:
    image: postgis/postgis:latest
    restart: unless-stopped
    volumes:
      - test-postgres-data:/var/lib/postgresql/data
    ports:
      - 5602:5432
    environment:
      POSTGRES_PASSWORD: pguser
      POSTGRES_USER: pguser
      POSTGRES_DB: test_db
    networks:
      - localnet

volumes:
  test-postgres-data:
```

2. Start up Codespace and in terminal, confirm db container is running via `docker ps`. E.g. 

![Image](https://github.com/user-attachments/assets/5bd5cefc-1c4f-4366-b792-7b0483ed6264)

4. Connect to db via Azure Data Studio and confirm connection works.  E.g.
    - Connection Type: PostgreSQL
    - Server name: localhost
    - Authentication Type: Password
    - User name: pguser
    - Password: pguser
    - Database name: test_db
    - Advanced --> Host IP Address: 127.0.0.1
    - Advanced --> Port: 5602
5. Attempt to connect to db via VSCode using Microsoft's PostgreSQL extension with settings:    
    - Server Name: 127.0.0.1
    - Authentication Type: Password
    - User Name: pguser
    - Password: pguser
    - Database Name: test_db
    - Advanced --> Ports: 5602
    - Click "Test Connection"
     
**Expected behavior**
- Connection successful

**Actual behavior**
- Connection failed: 

![Image](https://github.com/user-attachments/assets/0d4acede-e163-46e3-9002-906cd36d20d2)

^ NOTE: if Codespace setup was the issue, then Azure Data Studio should also fail, but it connects.

Sharing `Code -> About Visual Studio Code` (macOS) info:
![Image](https://github.com/user-attachments/assets/474831f0-4f7c-4f72-a2fd-9b122b1c0155)
